### ISSUE TITLE
Use zxcvbn (or its newer variants) instead of the plain entropy formula

### ISSUE THREAD

**Issue by dumblob** [edoardottt/pwdsafety#19]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see people believing plain entropy mantra.

**Describe the solution you'd like**
Exchange the entropy formula for https://github.com/dropbox/zxcvbn or a newer variant of zxcvbn.

**Describe alternatives you've considered**
Leaving users to believe in a pure mathematical world where only entropy matters.

**Additional context**
Related:
https://github.com/edoardottt/pwdsafety/issues/18
https://github.com/edoardottt/pwdsafety/issues/15

**Comment by edoardottt** [comment]
Honestly Idk, I've done some tests, it's very easy to fool

**Comment by dumblob** [comment]
Awesome, thanks for testing!

Could you share your tests and the results side by side? That could shed some light on how to integrate both methods.

zxcvbn is a bunch of heuristics (based on plenty real-world observations) and less mathematics. So it is by far not bullet-proof. OTOH entropy-based estimations seem to work in practice only in those classes of scenarios where zxcvbn fails. The problem is to detect the classes of scenarios where zxcvbn does not work well :wink:.

**Comment by edoardottt** [comment]
I tried `ottavianelli` (my surname) and for zxcvbn it looks safe, while for pwdsafety it's very weak (2/10) because it finds that word in leaked passwords. 
Imo the problem with that tool is the fact that tries always to find a pattern in a password (for example: ott by bruteforce, avian by english vocabulary and elli as female name) where there isn't a pattern, it's just a word..  
And I agree with you, maybe an integration could be the solution.. but I don't know how 

btw I have never used y surname as pwd ahah, don't know why it's there

**Comment by edoardottt** [comment]
Closed due to inactivity.

**Comment by dumblob** [comment]
> I tried `ottavianelli` (my surname) and for zxcvbn it looks safe, while for pwdsafety it's very weak (2/10) because it finds that word in leaked passwords. Imo the problem with that tool is the fact that tries always to find a pattern in a password (for example: ott by bruteforce, avian by english vocabulary and elli as female name) where there isn't a pattern, it's just a word.. Out of that (let's say that tool recognize every pattern), knowing already the password it's easy to say "I find that part bruteforcing with the english vocabulary and the second part 4 random numbers", but there are still millions of combinations (first numbers then word, numbers interleaving letters...), how can an attacker choose the right pattern ?

There are billions of people in the world but only a few patterns all of these people usually come up with. An attacker has this finite short list of patterns too.

> And I agree with you, maybe an integration could be the solutionblush.. but I don't know how

The online check has to be always part of the default check. Then **both** zxcvbn (A) and your entropy formula (B) will be used. In case there is a huge disparity in A and B (one way or another), then the password is not secure. Simple as this (both remaining cases when A and B go along each other are clear). Now only to designate the threshold of disparity :wink:. So let us say if the difference is more than 30 percent points, then it becomes a disparity :wink:.
