### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by omnigenous** [edoardottt/pwdsafety#49]
https://aur.archlinux.org/

Please, consider publishing to Arch User Repositories!

**Comment by nizne9** [comment]
I've already packaged `pwdsafety` and `pwdsafety-bin` for the AUR. You can find them there.

**Comment by nizne9** [comment]
> https://aur.archlinux.org/
> 
> Please, consider publishing to Arch User Repositories!

I've already packaged `pwdsafety` and `pwdsafety-bin` for the AUR. You can find them there.
